### ISSUE TITLE
how to install izariam?

### ISSUE THREAD

**Issue by thiagopro** [ZZJHONS/IZARIAM#1]
how to install izariam?

**Comment by ZZJHONS** [comment]
http://ikariam.zzjhons.com/

**Comment by sk9c00** [comment]
hmm... the login window doesn't work...

**Comment by ZZJHONS** [comment]
You need edit the file application/config/ikariam.php:

$config['style_url'] = 'http://localhost/design/';
$config['script_url'] = 'http://localhost/design/';

**Comment by sk9c00** [comment]
Doesn't work... I used avo's version and it worked fine... The only problem I found was assigning people to work and I had a fun time editing the .htaccess file... Lol I had to disable the subdomain redirects as it caused a loop...

BTW I did edit that file...

I'm not sure if its me but the javascript animation doesn't work as well...
... maybe leech it off avo's one lolz?

**Comment by ZZJHONS** [comment]
You can login here: http://izariam.zzjhons.com/ ?

I deleted all files and upload the new version from github and it work (For me and others)

**Comment by sk9c00** [comment]
I know you can login on your server but not mine...

**Comment by sk9c00** [comment]
Anyway... is there a assign worker bug on yours?

**Comment by ZZJHONS** [comment]
What is your browser?

In the las update by haku it is fixed: 78dc6b70788feb784264f5e8e1faf34e69c2e314

**Comment by sk9c00** [comment]
When is the next update for the Skin and GUI done... I mean there is a new tutorial isn't there?

**Comment by ZZJHONS** [comment]
When the games works good

**Comment by sk9c00** [comment]
Do you need an English Translator?

**Comment by sk9c00** [comment]
or a grammar/format checker?

**Comment by sk9c00** [comment]
or a Wiki writer/Readme editor/instructions manager...

**Comment by ZZJHONS** [comment]
I don't speak english, if you want I reply you in Spanish and you Translate to english. OK?

**Comment by sk9c00** [comment]
depends on you...

**Comment by sk9c00** [comment]
I will start translating soon, as this seems to be a more promising project. I can only do the translations but if you could be kind enough to do some more bug fixes and possible add more configurable lang files...

**Comment by ZZJHONS** [comment]
No, translate the new release because i add more translation strings and changed the order and name of some

**Comment by ZZJHONS** [comment]
New version released, can start to translate

**Comment by sk9c00** [comment]
kk I will do when I find the time, soon...

On Sun, Feb 26, 2012 at 2:25 AM, ZZJHONS <
reply@reply.github.com
