### ISSUE TITLE
Cannot send ships when pillaging Barbarian Village

### ISSUE THREAD

**Issue by GTRsdk** [ZZJHONS/IZARIAM#12]
When I click Pillage on the Barbarian Village, it lets me select units to send, but I cannot select to send ships.

**Comment by ZZJHONS** [comment]
Pillage don't work
El 26/06/2012 19:49, "GTRsdk" <
reply@reply.github.com>
escribió:

**Comment by ZZJHONS** [comment]
Closed because Pillage will be added in the future, I need help!
