### ISSUE TITLE
Got Error Installation

### ISSUE THREAD

**Issue by nur1labs** [ZZJHONS/IZARIAM#14]
Warning: rename(include/­index.php,../­index.php) [function.rename]: File exists in C:\AppServ\www\Ikria­m_LE\install\install­.php on line 117

Warning: rename(include/­database.php,../­izariam/config/­database.php) [function.rename]: File exists in C:\AppServ\www\Ikria­m_LE\install\install­.php on line 118

Warning: rename(include/­config.php,../­izariam/config/­config.php) [function.rename]: File exists in C:\AppServ\www\Ikria­m_LE\install\install­.php on line 119

Warning: rename(include/­izariam.php,../­izariam/config/­izariam.php) [function.rename]: File exists in C:\AppServ\www\Ikria­m_LE\install\install­.php on line 120

Warning: Cannot modify header information - headers already sent by (output started at C:\AppServ\www\Ikria­m_LE\install\install­.php:117) in C:\AppServ\www\Ikria­m_LE\install\install­.php on line 121

**Comment by walle303** [comment]
Did you chmod -r 777 to the install folder

**Comment by nur1labs** [comment]
yes

**Comment by ZZJHONS** [comment]
Try using chmod -r 777 to all files only when install.

**Comment by nur1labs** [comment]
okay
