### ISSUE TITLE
new issue about recover password

### ISSUE THREAD

**Issue by etms51** [ZZJHONS/IZARIAM#2]
Description: When i want to recover the password, i click on the "Login" button on the homepage, open a small tooltip where i put the my data about login into my account, but i click on the "Forgot your password?" function.
Open a new screen where there is an error shown:  (Screenshot 1)

Step by Step:

1)I write the this url by my address bar of the my browser (http://izariam.zzjhons.com/)
2)I click on the "Login" button
3)Open a new small tooltip where i must enter my authenticate data for login into my account, but i click on the "Forgot your password" link function for recover the my password.
4)Show this error (Screenshot 1)

Error message: "A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: main/password.php

Line Number: 8"

Browser: Google Chrome v. 16.0.912.77
Screenshot:
image 1 => http://dl.dropbox.com/u/34043118/IZKARIAM/Recover_password_Link.jpg

please fix it.

**Comment by ZZJHONS** [comment]
Thanks, In the new version it work well. Can download now.
