### ISSUE TITLE
About Missing Buildings (Museum, Embassy, Temple, Workshop)

### ISSUE THREAD

**Issue by ekardon** [ZZJHONS/IZARIAM#8]
- Anyone has these buildings function codes or when will they available for downloading?
- Also, I encountered some errors in the game. where can I post them? (not the mail, forum posting)

**Comment by ZZJHONS** [comment]
Post in new issues the errors wich you found.

Missing building will be add soon in the future

**Comment by ZZJHONS** [comment]
@ekardon please, post the errors on new issues.

These buildings need be written.
