### ISSUE TITLE
Speed server

### ISSUE THREAD

**Issue by lumea** [ZZJHONS/IZARIAM#9]
how i raise the speed game?

**Comment by ZZJHONS** [comment]
For now you can't I will add it in the future

**Comment by lumea** [comment]
how much you are going to take to finish izariam?

a stable version

**Comment by ZZJHONS** [comment]
I haven't time now, but in the following summer i will do it

**Comment by lumea** [comment]
edit speed is very difficult???

**Comment by ZZJHONS** [comment]
yes, for now, but i will rewrite it

**Comment by lumea** [comment]
try to take the shortest possible time

**Comment by ZZJHONS** [comment]
The next month I will work in it 100% now i can't

**Comment by lumea** [comment]
the next month begins in 16 min in portugal

xD

**Comment by ZZJHONS** [comment]
In Spain now: 01/06/2012 00:48 ;) Next month :)

**Comment by lumea** [comment]
....

ok

if you have time you could put the speed thing...

i dont understand the task bug in travian

sorry

**Comment by lumea** [comment]
you go work in ikariam now?

xD
